

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web: # Flask app
    build: .
    container_name: sport-app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    

volumes:
  mariadb_data:
