"""add_preference_sport_table

Revision ID: 903043bc8299
Revises: f47ac10b58cc
Create Date: 2025-04-22 16:19:59.855135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903043bc8299'
down_revision: Union[str, None] = 'f47ac10b58cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_sport',
    sa.Column('preference_sport_id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=True),
    sa.Column('sport_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preference_id'], ['sport_preferences.preference_id'], ),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.sport_type_id'], ),
    sa.PrimaryKeyConstraint('preference_sport_id')
    )
    op.create_index(op.f('ix_preference_sport_preference_sport_id'), 'preference_sport', ['preference_sport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_sport_preference_sport_id'), table_name='preference_sport')
    op.drop_table('preference_sport')
    # ### end Alembic commands ###
