"""init

Revision ID: 9dde57c6fd53
Revises: 
Create Date: 2025-04-19 18:22:24.971816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dde57c6fd53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True, comment='縣市'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='鄉鎮市區'),
    sa.Column('is_first_login', sa.Boolean(), nullable=True, server_default=sa.sql.expression.true(), comment='是否為第一次登入'),
    sa.Column('is_unfinish_preference', sa.Boolean(), nullable=True, server_default=sa.sql.expression.true(), comment='是否完成偏好'),
    sa.Column('public_intro', sa.String(length=500), nullable=True, comment='公開介紹'),
    sa.Column('facebook_url', sa.String(length=255), nullable=True, comment='Facebook 連結'),
    sa.Column('instagram_url', sa.String(length=255), nullable=True, comment='Instagram 連結'),
    
    
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=False)
    op.create_table('sport_types',
    sa.Column('sport_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('sport_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sport_types_sport_type_id'), 'sport_types', ['sport_type_id'], unique=False)
    op.create_table(
    'activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_lat', sa.DECIMAL(18, 15), nullable=True),
    sa.Column('location_lng', sa.DECIMAL(18, 15), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=True, server_default="0"),
    sa.Column('organizer_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('sport_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('has_review', sa.Boolean(), nullable=True),
    sa.Column('target_identity', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('venue_fee', sa.DECIMAL(10, 2), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['members.member_id']),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.sport_type_id']),
    sa.PrimaryKeyConstraint('activity_id')
)

    op.create_index(op.f('ix_activities_activity_id'), 'activities', ['activity_id'], unique=False)
    op.create_table('exercise_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('sport_type_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('intensity_level', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.sport_type_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_exercise_records_record_id'), 'exercise_records', ['record_id'], unique=False)
    op.create_table('sport_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('match_gender', sa.String(length=10), nullable=True),  # 加入性別欄位
    sa.Column('match_age', sa.String(length=20), nullable=True),     # 加入年齡欄位
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index(op.f('ix_sport_preferences_preference_id'), 'sport_preferences', ['preference_id'], unique=False)
    op.create_table('user_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('target_member_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.Integer(), sa.ForeignKey('activities.activity_id'), nullable=True),
    sa.Column('template_ids', sa.JSON, nullable=True),

    sa.ForeignKeyConstraint(['reviewer_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['target_member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_user_reviews_review_id'), 'user_reviews', ['review_id'], unique=False)
    op.create_table('activity_joins',
    sa.Column('join_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('has_review', sa.Boolean(), nullable=True),
    sa.Column('is_checked_in', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('join_id')
    )
    op.create_index(op.f('ix_activity_joins_join_id'), 'activity_joins', ['join_id'], unique=False)
    op.create_table('activity_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('template_ids', sa.JSON, nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
 
    op.create_index(op.f('ix_activity_reviews_review_id'), 'activity_reviews', ['review_id'], unique=False)

    op.create_table('preference_sport',
        sa.Column('preference_id', sa.Integer(), nullable=False),
        sa.Column('sport_type_id', sa.Integer(), nullable=False),
        
        # 設定外鍵約束
        sa.ForeignKeyConstraint(['preference_id'], ['sport_preferences.preference_id']),
        sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.sport_type_id']),
        
        # 設為複合主鍵
        sa.PrimaryKeyConstraint('preference_id', 'sport_type_id')
    )

    # 設定唯一約束
    op.create_index('ix_preference_sport_preference_id_sport_type_id', 'preference_sport', ['preference_id', 'sport_type_id'], unique=True)
    
    op.create_table(
        'time_option',
        sa.Column('time_id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('period', sa.String(length=50), nullable=False),  # 平日或周末
        sa.Column('time_of_day', sa.String(length=50), nullable=False),  # 早上、中午或晚上
        sa.Column('label', sa.String(length=100), nullable=False),  # 時間描述
    )
    op.create_index('ix_time_option_period_time_of_day', 'time_option', ['period', 'time_of_day'], unique=False)


    op.create_table(
        'preference_time',
        sa.Column('preference_id', sa.Integer(), nullable=False),  # 外鍵
        sa.Column('time_id', sa.Integer(), nullable=False),  # 外鍵
        sa.ForeignKeyConstraint(['preference_id'], ['sport_preferences.preference_id']),
        sa.ForeignKeyConstraint(['time_id'], ['time_option.time_id']),
        sa.PrimaryKeyConstraint('preference_id', 'time_id'),
    )
    
    # 設定唯一約束
    op.create_index('ix_preference_time_preference_id_time_id', 'preference_time', ['preference_id', 'time_id'], unique=True)

    op.create_table(
    'course_schedule',
    sa.Column('course_schedule_id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id']),
)
    op.create_table(
        'review_templates',
        sa.Column('template_id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('text', sa.String(length=255), nullable=False),
    )
    op.create_table(
        'activity_favorite',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('member_id', sa.String(length=36), nullable=True),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.ForeignKeyConstraint(['member_id'], ['members.member_id']),
        sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id']),
        sa.UniqueConstraint('member_id', 'activity_id', name='uq_member_activity')
    )
    op.create_index('ix_activity_favorite_id', 'activity_favorite', ['id'], unique=False)
    op.create_table(
    'blacklist',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_member_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id']),
    sa.ForeignKeyConstraint(['blocked_member_id'], ['members.member_id']),
    )
    op.create_index('ix_blacklist_id', 'blacklist', ['id'], unique=False)

    op.create_table(
        'photo',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('file_path', sa.String(length=255), nullable=False),
        sa.Column('member_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['member_id'], ['members.member_id'])
    )
    op.create_index('ix_photo_id', 'photo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_reviews_review_id'), table_name='activity_reviews')
    op.drop_table('activity_reviews')
    op.drop_index(op.f('ix_activity_joins_join_id'), table_name='activity_joins')
    op.drop_table('activity_joins')
    op.drop_index(op.f('ix_user_reviews_review_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index(op.f('ix_sport_preferences_preference_id'), table_name='sport_preferences')
    op.drop_table('sport_preferences')
    op.drop_index(op.f('ix_exercise_records_record_id'), table_name='exercise_records')
    op.drop_table('exercise_records')
    op.drop_index(op.f('ix_activities_activity_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_sport_types_sport_type_id'), table_name='sport_types')
    op.drop_table('sport_types')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_table('members')
    op.drop_index('ix_preference_sport_preference_id_sport_type_id', table_name='preference_sport')
    op.drop_table('preference_sport')
    op.drop_index('ix_time_option_period_time_of_day', table_name='time_option')
    op.drop_table('time_option')
    op.drop_index('ix_preference_time_preference_id_time_id', table_name='preference_time')
    op.drop_table('preference_time')
    op.drop_index('ix_course_schedule_activity_id', table_name='course_schedule')
    op.drop_table('course_schedule')
    op.drop_table('review_templates')
    op.drop_index('ix_activity_favorite_id', table_name='activity_favorite')
    op.drop_table('activity_favorite')
    op.drop_index('ix_blacklist_id', table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_index('ix_photo_id', table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
