"""add min_age and max_age to activities

Revision ID: d51cf5fe9949
Revises: f47ac10b58cc
Create Date: 2025-04-25 17:49:19.442657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51cf5fe9949'
down_revision: Union[str, None] = 'f47ac10b58cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('max_age', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('is_first_login', sa.Boolean(), nullable=True, comment='是否為第一次登入'))
    op.add_column('members', sa.Column('is_unfinish_preference', sa.Boolean(), nullable=True, comment='是否完成偏好'))
    op.drop_index('ix_preference_sport_preference_id_sport_type_id', table_name='preference_sport')
    op.create_unique_constraint('uq_preference_sport_id', 'preference_sport', ['preference_id', 'sport_type_id'])
    op.drop_index('ix_preference_time_preference_id_time_id', table_name='preference_time')
    op.create_unique_constraint('uq_preference_time_id', 'preference_time', ['preference_id', 'time_id'])
    op.drop_index('ix_time_option_period_time_of_day', table_name='time_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_time_option_period_time_of_day', 'time_option', ['period', 'time_of_day'], unique=False)
    op.drop_constraint('uq_preference_time_id', 'preference_time', type_='unique')
    op.create_index('ix_preference_time_preference_id_time_id', 'preference_time', ['preference_id', 'time_id'], unique=True)
    op.drop_constraint('uq_preference_sport_id', 'preference_sport', type_='unique')
    op.create_index('ix_preference_sport_preference_id_sport_type_id', 'preference_sport', ['preference_id', 'sport_type_id'], unique=True)
    op.drop_column('members', 'is_unfinish_preference')
    op.drop_column('members', 'is_first_login')
    op.drop_column('activities', 'max_age')
    op.drop_column('activities', 'min_age')
    # ### end Alembic commands ###
