"""rebuild correct activity columns

Revision ID: d83b4ab2552d
Revises: f47ac10b58cc
Create Date: 2025-05-01 17:23:56.726202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd83b4ab2552d'
down_revision: Union[str, None] = 'f47ac10b58cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('identity', sa.String(length=50), nullable=True))
    op.add_column('activities', sa.Column('target_identity', sa.String(length=50), nullable=True))
    op.add_column('activities', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('activities', sa.Column('age_range', sa.String(length=20), nullable=True))
    op.drop_column('activities', 'max_age')
    op.drop_column('activities', 'time')
    op.drop_column('activities', 'min_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('min_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('time', mysql.DATETIME(), nullable=True))
    op.add_column('activities', sa.Column('max_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('activities', 'age_range')
    op.drop_column('activities', 'gender')
    op.drop_column('activities', 'target_identity')
    op.drop_column('activities', 'identity')
    op.drop_column('activities', 'end_time')
    op.drop_column('activities', 'start_time')
    # ### end Alembic commands ###
