"""Remove join_time from ActivityJoin

Revision ID: e7534fbd8cc4
Revises: f47ac10b58cc
Create Date: 2025-05-09 18:09:35.804654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7534fbd8cc4'
down_revision: Union[str, None] = 'f47ac10b58cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preference_sport_preference_id_sport_type_id', table_name='preference_sport')
    op.create_unique_constraint('uq_preference_sport_id', 'preference_sport', ['preference_id', 'sport_type_id'])
    op.drop_index('ix_preference_time_preference_id_time_id', table_name='preference_time')
    op.create_unique_constraint('uq_preference_time_id', 'preference_time', ['preference_id', 'time_id'])
    op.drop_index('ix_time_option_period_time_of_day', table_name='time_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_time_option_period_time_of_day', 'time_option', ['period', 'time_of_day'], unique=False)
    op.drop_constraint('uq_preference_time_id', 'preference_time', type_='unique')
    op.create_index('ix_preference_time_preference_id_time_id', 'preference_time', ['preference_id', 'time_id'], unique=True)
    op.drop_constraint('uq_preference_sport_id', 'preference_sport', type_='unique')
    op.create_index('ix_preference_sport_preference_id_sport_type_id', 'preference_sport', ['preference_id', 'sport_type_id'], unique=True)
    # ### end Alembic commands ###
